name: Spring Authorization Server docker image (make)

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/authorization-server-make.yaml
      - selenium/authorization-server
  pull_request:
    paths:
      - .github/workflows/authorization-server-make.yaml
      - selenium/authorization-server
  
env:
  REGISTRY_IMAGE: pivotalrabbitmq/spring-authorization-server
  IMAGE_TAG: 0.0.1
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v4

      - name: Prepare image        
        run: |
          ls        
          echo "Building spring authorization server"
          cd selenium/authorization-server
          docker build . -t authorization-server
          docker tag authorization-server ${{ env.REGISTRY_IMAGE }}:${{ env.IMAGE_TAG }} 
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push
        run: |
          docker push ${{ env.REGISTRY_IMAGE }}:${{ env.IMAGE_TAG }}