name: "Trigger a 4.0.x alpha release build"
on:
  workflow_dispatch:
  push:
    branches:
      - "v4.0.x"
    paths:
      - "deps/*/src/**"
      - 'deps/rabbitmq_management/priv/**'
      - ".github/workflows/**"
env:
  DEV_WORKFLOW_REPOSITORY: "rabbitmq/server-packages"
jobs:
  trigger_alpha_build:
    runs-on: ubuntu-latest
    steps:
      - name: Compute prerelease identifier from commit SHA
        run: echo "PRERELEASE_IDENTIFIER=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
      - name: Compute human-readable release timestamp
        run: echo "PRERELEASE_TIMESTAMP=`date --rfc-3339=seconds`" >> $GITHUB_ENV
      - name: Compute UNIX release timestamp
        run: echo "PRERELEASE_UNIX_TIMESTAMP=`date +%s`" >> $GITHUB_ENV
      - name: Trigger an alpha release build in ${{ env.DEV_WORKFLOW_REPOSITORY }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.RABBITMQCI_BOT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ env.DEV_WORKFLOW_REPOSITORY }}/dispatches \
            -d '{ "event_type": "new_4.0.x_alpha", "client_payload": {"release_repository": "${{ env.DEV_WORKFLOW_REPOSITORY }}", "release_description": "Commit: https://github.com/rabbitmq/rabbitmq-server/commit/${{ github.sha }}, build was triggered at: ${{ env.PRERELEASE_TIMESTAMP }}", "prerelease": true, "prerelease_kind": "alpha", "prerelease_identifier": "${{ env.PRERELEASE_IDENTIFIER }}", "release_title": "RabbitMQ 4.0.4-alpha.${{ env.PRERELEASE_IDENTIFIER }} (${{ env.PRERELEASE_TIMESTAMP }})", "base_version": "4.0.4", "release_timestamp": "${{ env.PRERELEASE_TIMESTAMP }}", "release_unix_timestamp": "${{ env.PRERELEASE_UNIX_TIMESTAMP }}" }}'
