name: Test mixed clusters (scheduled)
on:
  push:
  workflow_dispatch:
    inputs:
      erlang_version:
        description: 'Erlang version'
        required: true
        default: '28'
        type: string
      elixir_version:
        description: 'Elixir version'
        required: true
        default: '1.18'
        type: string
      metadata_store:
        description: 'Metadata store'
        required: true
        default: 'mnesia'
        type: choice
        options:
          - mnesia
          - khepri
      previous_version:
        description: 'Previous version to test against'
        required: true
        default: 'tags/v3.13.7'
        type: string
      previous_otp_version:
        description: 'Erlang version for previous RabbitMQ version'
        required: true
        default: '26'
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test-mixed-clusters:
    name: Test mixed clusters
    uses: ./.github/workflows/test-make-tests.yaml
    with:
      erlang_version: ${{ inputs.erlang_version }}
      elixir_version: ${{ inputs.elixir_version }}
      metadata_store: ${{ inputs.metadata_store }}
      mixed_clusters: true
      previous_version: ${{ inputs.previous_version }}
      previous_otp_version: ${{ inputs.previous_otp_version }}
